dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN

cache:
  directories:
    "$HOME/.m2"
script:
  "mvn clean install"
